/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.floodplain.redpanda;

import org.apache.kafka.clients.admin.AdminClient;
import org.apache.kafka.clients.admin.AdminClientConfig;
import org.apache.kafka.clients.admin.NewTopic;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutionException;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testAdminClient() throws ExecutionException, InterruptedException {
        Map<String,Object> config = new HashMap<>();
        config.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG,"localhost:9092");
        AdminClient adminClient = AdminClient.create(config);
        adminClient.listTopics().names().get().forEach(i->
            System.err.println("topic found: "+i)
        );
    }

//    NewTopic nt = new NewTopic("somename",1,(short)1);
//        Arrays.asList(nt);
//        adminClient.createTopics(Arrays.asList(nt)).all().get();
//        System.err.println("created");
}
